const events = [
  {
    id: 1,
    title: "Tech Meetup",
    date: "2023-08-15",
    duration: "2 hours",
    location: "Tech Hub",
    description: "A meetup for tech enthusiasts to discuss the latest trends.",
    joinedUsers: [
      "User1",
      "User2",
      "User3",
      "User4",
      "User5",
      "User6",
      "User7",
      "User8",
      "User9",
      "User10",
    ],
  },
  {
    id: 2,
    title: "Fitness Class",
    date: "2023-08-20",
    duration: "1.5 hours",
    location: "Fitness Center",
    description: "Join us for an energetic fitness class.",
    joinedUsers: [
      "User1",
      "User2",
      "User3",
      "User4",
      "User5",
      "User6",
      "User7",
      "User8",
      "User9",
      "User10",
      "User11",
      "User12",
      "User13",
      "User14",
      "User15",
    ],
  },
  {
    id: 3,
    title: "Art Exhibition",
    date: "2023-09-01",
    duration: "3 hours",
    location: "Art Gallery",
    description:
      "Explore the creativity of local artists at our art exhibition.",
    joinedUsers: [
      "User16",
      "User17",
      "User18",
      "User19",
      "User20",
      "User21",
      "User22",
      "User23",
      "User24",
      "User25",
    ],
  },
  {
    id: 4,
    title: "Cooking Workshop",
    date: "2023-09-10",
    duration: "2.5 hours",
    location: "Culinary School",
    description: "Learn to cook delicious dishes from professional chefs.",
    joinedUsers: [
      "User26",
      "User27",
      "User28",
      "User29",
      "User30",
      "User31",
      "User32",
      "User33",
      "User34",
      "User35",
    ],
  },
  {
    id: 5,
    title: "Book Club Meeting",
    date: "2023-09-25",
    duration: "1 hour",
    location: "Library",
    description:
      "Join us for a discussion on the latest book in our book club.",
    joinedUsers: [
      "User36",
      "User37",
      "User38",
      "User39",
      "User40",
      "User41",
      "User42",
      "User43",
      "User44",
      "User45",
    ],
  },
];

export default events;
